language: python
python:
  - "2.7.10"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - flake8 ./ --config=protocol/flake8
  - nosetests -v --with-coverage --cover-package=lib/forward

notifications:
  email:
      recipients:
        - azrael-ex@139.com
      on_success: always
      on_failure: always

after_success:
- coveralls
